### ISSUE TITLE
Check COVID algorithm

### ISSUE THREAD

**Issue by knthompson26** [klpurves/PANCHANGE_scripts#10]
I have written a basic chunk to run the COVID/Zoe algorithm, but this will need checking and some discussion about how to use this in RAMP (due to age and sex/gender variables). 
- [ ] Gender would need to be split into a binary variable. 
-  [ ] Age is expected to be continuous so would need to consider how to address this in RAMP. 
- [ ] Need to double check the cut offs for the COVID probability. Does the STATA code mean three groups or two with a cut off at 0.5?

**Comment by klpurves** [comment]
Is this our best reference for this algorithm @knthompson26 ?

https://covid.joinzoe.com/post/how-we-are-predicting-covid-in-the-uk

**Comment by knthompson26** [comment]
@klpurves Sorry only just seen this - algorithm comes from: [https://www.nature.com/articles/s41591-020-0916-2.pdf](url)

The paper states to use the cut off of 0.5 to create two groups - so I have edited the code accordinly and checked with the COVIDENCE group that they are doing the same.

**Comment by knthompson26** [comment]
@klpurves I have had confirmation from the COVIDENCE team that they use 0.5 as a cut off - so will be two binary groups - have edited the script accordingly and will close this issue. There is another issue of how to address this in RAMP.
