### ISSUE TITLE
Archive OCI-R and difference scores, regression models we aren't using (keep model 1b only) 

### ISSUE THREAD

**Issue by klpurves** [klpurves/PANCHANGE_scripts#103]
Not consistent with the other three disorders and underpowered due to gating.

This needs more thought and sensitive exploration as paper in its own right with a consultation with Gerogina and other clinical researchers

**Comment by knthompson26** [comment]
I was originally assigned this but I'm not sure which models are the definitive ones - plus this should probably be done at the end when cleaning/moving files into the correct folders
