### ISSUE TITLE
Create colour palette document 

### ISSUE THREAD

**Issue by knthompson26** [klpurves/PANCHANGE_scripts#12]
Need to create a document that defines each of the colour palettes identified in the preprocessing script. What colours are they? Are they related to logos? Are they colour blind friendly? 

@topherhuebel specifically requested this in the script.

**Comment by klpurves** [comment]
This is a good point. 
I find this site helpful for complementary palettes, and which includes colour blind simulations for each colour. 

https://convertingcolors.com/
