### ISSUE TITLE
Create IBD exclusion chunk in preprocessing

### ISSUE THREAD

**Issue by knthompson26** [klpurves/PANCHANGE_scripts#18]
Create a chunk that accounts for the exclusion of inflammatory bowel disease in National BioResource cohort. This is to make sure that we aren't oversampling for IBD in our sample. 

- alternatively sample according to IBD prevalence in UK population

- What is the IBD prevalence in the UK population? -> Literature search

- This chunk needs to be included when we have the data available from the NBR

**Comment by topherhuebel** [comment]
https://pubmed.ncbi.nlm.nih.gov/32690524/

Point prevalence estimates on 31 December 2018 for IBD overall, CD and UC were 725, 276 and 397 per 100 000 people, respectively.

**Comment by topherhuebel** [comment]
IBD 0.00725

CD 0.00276

UC 0.00397

**Comment by mollyrdavies** [comment]
I've written this chunk in the script. 3,410 NBR IBD participants were excluded. Made a note in the script as well. #44
