### ISSUE TITLE
Create comorbidity variable/group

### ISSUE THREAD

**Issue by knthompson26** [klpurves/PANCHANGE_scripts#34]
- [ ] create variable comorbidity count: sum the number of diagnoses and subtract 1 

- [ ] create total disorder count: sum the number of diagnoses

- [ ] create a comorbid anxiety and depression group - have depression only, anxiety only and anxiety+depression

- [ ] Cut the variable comorbidity count into categories.

**Comment by topherhuebel** [comment]
I have created total disorder count, total comorbidity count, and also a categorical version (as Gerome suggested) of the comorbidity count
