### ISSUE TITLE
Add analyst information file

### ISSUE THREAD

**Issue by klpurves** [klpurves/PANCHANGE_scripts#5]
We need a file with agreed conventions for how we will name branches and files, and what our basic workflow will be on github.

it would be helpful to have a section that describes what labels we will use for issues (i.e. meeting topic, analysis, dataviz) and that we will make sure to assign someone each task and review we raise.

**Comment by knthompson26** [comment]
@klpurves I have added this document for you and @mollyrdavies to review. Please add anything you think I have missed. Also ignore the naming of this branch!!
