### ISSUE TITLE
Ethnic groupings

### ISSUE THREAD

**Issue by mollyrdavies** [klpurves/PANCHANGE_scripts#71]
Need to decide what to do with the Arab grouping - discussion for the meeting.

**Comment by klpurves** [comment]
Tricky one. Doing a bit of reading on it, seems as if effectively Arabic origins fall broadly into "MIddle Eastern and North African". So I suppose given our categories, Including them where we would North African is probably out best bet.

**Comment by mollyrdavies** [comment]
@klpurves Gerome had apparently suggested that we include Arabs with the Europeans, because genetically they are most similar. However, regardless of genetics, for a phenotypic paper on the impact of Covid in the UK, I don't think that decision would make sense. Put it here as a discussion point for next meeting!

**Comment by mollyrdavies** [comment]
Also at the moment "Other ethnic group" is being recoded as "Asian or Asian British". Wondering if this is a mistake or a decision that was made? @topherhuebel @klpurves

**Comment by klpurves** [comment]
> Also at the moment "Other ethnic group" is being recoded as "Asian or Asian British". Wondering if this is a mistake or a decision that was made? @topherhuebel @klpurves

I'd say a mistake. Definitely can't classify the other group as Asian or Asian British. Maybe need to check our recoding on Qualtrics.

**Comment by mollyrdavies** [comment]
I've now changed the analysis script so that the Other ethnic category is kept. Just need to decide how to categorise Arab (at the moment it's part of the African grouping)
