### ISSUE TITLE
Add sensitivity analyses: GLAD cut-offs

### ISSUE THREAD

**Issue by klpurves** [klpurves/PANCHANGE_scripts#93]
Add chunk:

Model 1b absolute scores, controlling for pre-pandemic stratified by sign up to GLAD (restricting to 3, 6, 9 months before pandemic).

Variables created, need to sue this to create subsetted datasets to run our script.

**Comment by knthompson26** [comment]
Created pull request to close this issue. 

I reran models 1b absolute values for GAD, PHQ and PCL in subsets of the GLAD sample that signed up in the 3 months, 6 months and 9 months prior to the pandemic. I did this through the following steps:

1) created date and binary variables to identify who signed up to GLAD within the given time period
2) created subsets of the dataset according to those who signed up 3 months prior, 6 months prior and 9 months prior. All data sets are inclusive i.e. those who are in the 3 month dataset are also in the 6 and 9 month dataset.
4) Reran the 1b absolute score models for GAD in groups for 3, 6, 9 months
5) Reran the 1b absolute score models for PHQ in groups for 3, 6, 9 months
6) Reran the 1b absolute score models for PCL in groups for 3, 6, 9 months
